name: Deploy Edge Functions

on:
  push:
    branches:
      - master  # Dispara o workflow ao fazer push na branch "master"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Escolha a versão Node.js necessária

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_TOKEN }}    

      # Instalação do Supabase CLI usando o método recomendado (npx)
      - name: Deploy Edge Function
        run: npx supabase functions deploy hello-world --project-ref kubeteoyowktehmkjbzv
