name: Deploy Edge Functions

on:
  push:
    branches:
      - master  # Dispara o workflow ao fazer push na branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/x/install/install.sh | sh
          export DENO_INSTALL="/home/runner/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"

      - name: Install Supabase CLI
        run: deno install -A -f -n supabase https://deno.land/x/supabase_cli/main.ts

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy Edge Function
        run: supabase functions deploy hello-world --project-ref kubeteoyowktehmkjbzv
