name: Deploy Edge Functions

on:
  push:
    branches:
      - main  # Dispara o workflow ao fazer push na branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Escolha a versão Node.js necessária

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy Edge Function
        run: supabase functions deploy minha-funcao --project-ref kubeteoyowktehmkjbzv
